Add Ghostty configuration and colors
AlexvZyl/nordic.nvim pull request #160
Opened 2024-10-27 20:49 UTC by jorgebef

Add Ghostty colors and configuration as well as a very short readme to explain how to set it up.

2024-10-28 20:36 UTC, 5-pebbles commented
can you share some screenshots, please and thank you?

On Sunday, October 27th, 2024 at 4:49 PM, Jorge B ***@***.***> wrote:

> Add Ghostty colors and configuration as well as a very short readme to explain how to set it up.
>
> ---------------------------------------------------------------
>
> You can view, comment on, or merge this pull request online at:
>
> https://github.com/AlexvZyl/nordic.nvim/pull/160
>
> Commit Summary
>
> - [f05b6a0](https://github.com/AlexvZyl/nordic.nvim/pull/160/commits/f05b6a05fd2916dec1d1f2ef5b684ae0b758bbf9) Add Ghostty configuration and colors
>
> File Changes
>
> ([2 files](https://github.com/AlexvZyl/nordic.nvim/pull/160/files))
>
> -  A [platforms/ghostty/README.md](https://github.com/AlexvZyl/nordic.nvim/pull/160/files#diff-b32e977112f5236971eedb009c43f451f78c1f8779a147fcac5eddb98384c365) (12)
> -  A [platforms/ghostty/nordic](https://github.com/AlexvZyl/nordic.nvim/pull/160/files#diff-614f106182ded97c6bbda6159671015b307ff388e96caae48c3008c98c4eaa29) (27)
>
> Patch Links:
>
> - https://github.com/AlexvZyl/nordic.nvim/pull/160.patch
> - https://github.com/AlexvZyl/nordic.nvim/pull/160.diff
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/AlexvZyl/nordic.nvim/pull/160), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/BFBVZ2DSC75XPHXDH2PL2PTZ5U7VZAVCNFSM6AAAAABQWE6UOWVHI2DSMVQWIX3LMV43ASLTON2WKOZSGYYTMOBWGAZTENQ).
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2024-10-29 21:43 UTC, jorgebef commented
Here are a couple of screenshots as well as one from neovim to compare:
<img width="1267" alt="Screenshot 2024-10-29 at 22 15 59" src="https://github.com/user-attachments/assets/def90583-7a28-4c93-9273-e8079e35d9bd">
<img width="645" alt="Screenshot 2024-10-29 at 22 14 06" src="https://github.com/user-attachments/assets/fdd84961-9da4-4560-8bcb-d5828b99431f">
<img width="1150" alt="Screenshot 2024-10-29 at 22 11 54" src="https://github.com/user-attachments/assets/7e87369d-2e43-4e48-a38c-478f5625feaf">
<img width="686" alt="Screenshot 2024-10-29 at 22 43 07" src="https://github.com/user-attachments/assets/40c92474-1733-423b-ba74-170e02cddbcc">

2024-12-29 14:06 UTC, AlexvZyl commented
Sweet, thanks @.

Why did you modify source files?  That should not be relevant to this PR.

2024-12-29 14:07 UTC, AlexvZyl requested changes
Please only add the relevant files for ghostty.

2025-01-12 17:05 UTC, AlexvZyl approved these changes

2025-01-12 17:09 UTC, 5-pebbles approved these changes
Looks good to me!

2025-01-12 17:14 UTC, merged